package com.bacancy.ccs2androidhmi.util

object ResponseSizes {

    const val LAST_CHARGING_SUMMARY_RESPONSE_SIZE = 47
    const val GUN_INFORMATION_RESPONSE_SIZE = 41
    const val AC_METER_INFORMATION_RESPONSE_SIZE = 53
    const val AC_CHARGER_AC_METER_INFORMATION_RESPONSE_SIZE = 53
    const val GUN_DC_METER_INFORMATION_RESPONSE_SIZE = 41
    const val MISC_INFORMATION_RESPONSE_SIZE = 155

}