package com.bacancy.ccs2androidhmi.util

object ResponseSizes {

    const val LAST_CHARGING_SUMMARY_RESPONSE_SIZE = 47
    const val GUN_INFORMATION_RESPONSE_SIZE = 49
    const val AC_METER_INFORMATION_RESPONSE_SIZE = 53
    const val AC_CHARGER_AC_METER_INFORMATION_RESPONSE_SIZE = 53
    const val GUN_DC_METER_INFORMATION_RESPONSE_SIZE = 41
    const val MISC_INFORMATION_RESPONSE_SIZE = 155
    const val SINGLE_REGISTER_RESPONSE_SIZE = 7 //2 + 5
    const val CONFIGURATION_PARAMETERS_RESPONSE_SIZE = 95

}